// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetAPI.Infrastructure.Data;

namespace PetAPI.Infrastructure.Migrations
{
    [DbContext(typeof(AnimalContext))]
    partial class AnimalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("PetAPI.Core.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Name");

                    b.Property<int>("ShelterId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("ShelterId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 2,
                            Name = "Chewie",
                            ShelterId = 1,
                            Type = "Dog"
                        },
                        new
                        {
                            Id = 2,
                            Age = 7,
                            Name = "Han",
                            ShelterId = 2,
                            Type = "Dog"
                        });
                });

            modelBuilder.Entity("PetAPI.Core.Models.Shelter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.ToTable("Shelters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "3323 SE Loop 289, Lubbock, TX 79404",
                            Name = "Lubbock Animal Shelter & Adoption Center",
                            Phone = "(806) 775-2057"
                        },
                        new
                        {
                            Id = 2,
                            Address = "4501 Farm to Market Rd 1729, Lubbock, TX 79403",
                            Name = "Haven Animal Care Shelter",
                            Phone = "(806) 763-0092"
                        });
                });

            modelBuilder.Entity("PetAPI.Core.Models.Animal", b =>
                {
                    b.HasOne("PetAPI.Core.Models.Shelter", "Shelter")
                        .WithMany("Animals")
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
